spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_security
    username: alibou
    password: alibou
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
access-token:
  private: ${ACCESS_TOKEN_PRIVATE_PATH}
  public: ${ACCESS_TOKEN_PUBLIC_PATH}
refresh-token:
    private: ${REFRESH_TOKEN_PRIVATE_PATH}
    public: ${REFRESH_TOKEN_PUBLIC_PATH}